function [ACCX, ACCY, ACCZ, GX, GY, GZ] = getData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [ACCX, ACCY, ACCZ, GX, GY, GZ] = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as
%  column vectors.
%
%  [ACCX, ACCY, ACCZ, GX, GY, GZ] = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [ACCX, ACCY, ACCZ, GX, GY, GZ] = importfile("C:\Users\Mark\Dropbox\project_VRS\SensorData\putty.log", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Nov-2019 17:21:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ACCX", "ACCY", "ACCZ", "GX", "GY", "GZ"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
ACCX = tbl.ACCX;
ACCY = tbl.ACCY;
ACCZ = tbl.ACCZ;
GX = tbl.GX;
GY = tbl.GY;
GZ = tbl.GZ;
end